name: medsur_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+6

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: 4.5.1
  connectivity: ^3.0.6
  flutter_spinkit: any
  permission_handler: any
  sqflite: ^2.0.0+3
  loading_indicator: ^3.0.2
  cupertino_icons: ^1.0.2
  intl:
  pinput: any
  # agora_rtc_engine: ^6.1.0
  carousel_slider: ^4.0.0
  custom_navigation_bar: ^0.8.2
  flutter_svg: ^2.0.5
  geolocator: ^8.0.1
  date_input_field: ^0.0.3
  flutter_sound:
  # datetime_picker_formfield_new: ^2.1.0
  # custom_date_range_picker: ^1.0.10
  speech_to_text: ^6.1.1
  # intl_phone_field: ^3.1.0
  google_maps_flutter: ^2.2.8
  location: ^4.4.0
  url_launcher: ^6.0.6
  jwt_decoder: ^2.0.1
  time_picker_sheet: ^0.0.2+1
  time_picker_widget: ^1.0.0+10
  google_maps_webservice_ex: ^0.0.1+2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/images/logos/logo.png
    - assets/images/
    - assets/images/home/
    - assets/images/logos/
    - assets/images/background/
    - assets/svg/
    - assets/loader/
    - assets/svg/disconnexion_active.svg
    - assets/svg/user.svg
    - assets/svg/home.svg
    - assets/svg/activity.svg
    - assets/svg/listblanck.svg
    - assets/svg/globe.svg
    - assets/svg/squared-plus.svg
    - assets/svg/squared-minus.svg
    - assets/svg/category.svg
    - assets/svg/safe.svg
    - assets/svg/highquality.svg
    - assets/svg/high_quality.svg
    - assets/svg/w1.svg
    - assets/svg/w2.svg

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
